
name: "BNVD Security Enricher (Local)"
description: "Action local para enriquecimento de vulnerabilidades com BNVD/NVD"
author: "BNVD.org - Juan Mathews"

inputs:
  github_token:
    description: "Token do GitHub com permissão security-events:read"
    required: true
  bnvd_api_url:
    description: "URL base da API BNVD"
    required: false
    default: "https://bnvd.org/api/v1"
  nvd_api_key:
    description: "API key do NVD (opcional)"
    required: false
    default: ""
  include_pt:
    description: "Incluir traduções em português"
    required: false
    default: "true"
  severity_filter:
    description: "Filtrar por severidade: ALL, CRITICAL, HIGH, MEDIUM, LOW"
    required: false
    default: "ALL"
  fail_on_critical:
    description: "Falhar se encontrar vulnerabilidades críticas"
    required: false
    default: "false"
  fail_on_high:
    description: "Falhar se encontrar vulnerabilidades high+"
    required: false
    default: "false"
  output_format:
    description: "Formatos de saída: json, markdown, both"
    required: false
    default: "both"
  max_concurrent_requests:
    description: "Requisições paralelas máximas"
    required: false
    default: "5"
  request_timeout:
    description: "Timeout HTTP em segundos"
    required: false
    default: "30"
  retry_attempts:
    description: "Tentativas em caso de falha"
    required: false
    default: "3"

outputs:
  total_cves_found:
    description: "Número total de CVEs encontrados"
  total_enriched:
    description: "CVEs enriquecidos com BNVD/NVD"
  critical_count:
    description: "Vulnerabilidades críticas"
  high_count:
    description: "Vulnerabilidades high"
  medium_count:
    description: "Vulnerabilidades medium"
  low_count:
    description: "Vulnerabilidades low"
  has_critical:
    description: "Indica se há vulnerabilidades críticas"
  has_high:
    description: "Indica se há vulnerabilidades high+"
  cve_list:
    description: "Lista de CVEs (JSON)"
  execution_time:
    description: "Tempo de execução"
  report_json_path:
    description: "Caminho do relatório JSON"
  report_md_path:
    description: "Caminho do relatório Markdown"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0 PyGithub==2.1.1 tenacity==8.2.3

    - name: Run BNVD Enricher
      id: enricher
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_BNVD_API_URL: ${{ inputs.bnvd_api_url }}
        INPUT_NVD_API_KEY: ${{ inputs.nvd_api_key }}
        INPUT_INCLUDE_PT: ${{ inputs.include_pt }}
        INPUT_SEVERITY_FILTER: ${{ inputs.severity_filter }}
        INPUT_FAIL_ON_CRITICAL: ${{ inputs.fail_on_critical }}
        INPUT_FAIL_ON_HIGH: ${{ inputs.fail_on_high }}
        INPUT_OUTPUT_FORMAT: ${{ inputs.output_format }}
        INPUT_MAX_CONCURRENT_REQUESTS: ${{ inputs.max_concurrent_requests }}
        INPUT_REQUEST_TIMEOUT: ${{ inputs.request_timeout }}
        INPUT_RETRY_ATTEMPTS: ${{ inputs.retry_attempts }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: python ${{ github.action_path }}/src/main.py
